Allow `units-suggest` to suggest units for uninitialized variables (fixes #196)
camfort/camfort pull request #206
Opened 2024-09-30 14:52 UTC by dorchard

This fixes https://github.com/camfort/camfort/issues/196.
Previously 

```module unused_modvar
    implicit none
    real :: not_initialised
    real :: initialised = 5.0
end module
```
for `camfort units-suggest uninitialised.f90 -l poly` would only suggest that `initialised` needs annotating in poly mode or nothing in mixed mode. Now there is a new flag `--include-uninit` which gives:

```
% camfort units-suggest tests/fixtures/Specification/Units/uninitialised.f90 --include-uninit
Suggesting variables to annotate with unit specifications in 'tests/fixtures/Specification/Units/uninitialised.f90'
Successfully parsed 0 summary file(s).
Finished running unit critical variable analysis on input 'tests/fixtures/Specification/Units/uninitialised.f90' ...
Logs:

Result... OK:

tests/fixtures/Specification/Units/uninitialised.f90: 1 variable declarations suggested to be given a specification:
    tests/fixtures/Specification/Units/uninitialised.f90:5:13    not_initialised

% camfort units-suggest tests/fixtures/Specification/Units/uninitialised.f90 --include-uninit -l poly
Suggesting variables to annotate with unit specifications in 'tests/fixtures/Specification/Units/uninitialised.f90'
Successfully parsed 0 summary file(s).
Finished running unit critical variable analysis on input 'tests/fixtures/Specification/Units/uninitialised.f90' ...
Logs:

Result... OK:

tests/fixtures/Specification/Units/uninitialised.f90: 2 variable declarations suggested to be given a specification:
    tests/fixtures/Specification/Units/uninitialised.f90:7:13    initialised
    tests/fixtures/Specification/Units/uninitialised.f90:5:13    not_initialised
```

(with this branch of `fortran-src` https://github.com/camfort/fortran-src/pull/289)

2024-10-02 13:41 UTC, jaytorry commented
Note I think this PR address #187 (not #196)

2024-10-02 13:52 UTC, dorchard commented
> Note I think this PR address #187 (not #196)
Thanks. Fixed the PR description.

2024-10-02 14:02 UTC, jaytorry requested changes
This appears to resolve #187 - See below. 

However, the new _--include-uninit_ flag is also valid for _units-infer_, _units-check_, _units-synth_ and _units-compile_, and it is not clear if / how it affects these other commands. I recommend either clarifying this or restricting the flag to _units-suggest_ only. 

```
module unused_modvar

    implicit none

    real :: not_initialised

    real :: initialised = 5.0

end module
```
Without flag:
```
$ camfort units-suggest unused-modvar.f90 -l 'poly'
Suggesting variables to annotate with unit specifications in 'unused-modvar.f90'
Successfully parsed 0 summary file(s).
Finished running unit critical variable analysis on input 'unused-modvar.f90' ...
Logs:

Result... OK:

unused-modvar.f90: 1 variable declarations suggested to be given a specification:
    unused-modvar.f90:8:13    initialised
```
With flag (includes uninitialised): 
```
$ camfort units-suggest unused-modvar.f90 -l 'poly' --include-uninit
Suggesting variables to annotate with unit specifications in 'unused-modvar.f90'
Successfully parsed 0 summary file(s).
Finished running unit critical variable analysis on input 'unused-modvar.f90' ...
Logs:

Result... OK:

unused-modvar.f90: 2 variable declarations suggested to be given a specification:
    unused-modvar.f90:8:13    initialised
    unused-modvar.f90:6:13    not_initialised
```
**_units-infer_ behaves the same with or without the flag:** 
```
module unused_modvar

    implicit none

    != unit(m) :: not_initialised
    real :: not_initialised

    != unit(kg) :: initialised
    real :: initialised = 5.0

end module
```
```
$ camfort units-infer unused-modvar.f90 -l 'poly'
Inferring units for 'unused-modvar.f90'
Successfully parsed 0 summary file(s).
Finished running unit inference on input 'unused-modvar.f90' ...
Logs:

Result... OK:

unused-modvar.f90:
  7:13 unit m :: not_initialised
  10:13 unit kg :: initialised
```
```
$ camfort units-infer unused-modvar.f90 -l 'poly' --include-uninit
Inferring units for 'unused-modvar.f90'
Successfully parsed 0 summary file(s).
Finished running unit inference on input 'unused-modvar.f90' ...
Logs:

Result... OK:

unused-modvar.f90:
  7:13 unit m :: not_initialised
  10:13 unit kg :: initialised
```

2024-10-02 14:18 UTC, dorchard commented
This is a good point. It shouldn't do anything for `units-suggest` so I've changed it so it only allows this option for `units-suggest`.

2024-10-02 17:11 UTC, jaytorry approved these changes

2024-10-04 16:40 UTC, jaytorry commented
FYI - It looks like the wrong issue (#196) is still linked to this PR, so might get closed by mistake if/when the PR is merged? I couldn't unlink it manually.

2024-10-04 16:42 UTC, jaytorry commented
> FYI - It looks like the wrong issue (#196) is still linked to this PR, so might get closed by mistake if/when the PR is merged? I couldn't unlink it manually.

I have added the correct one anyway.

2024-10-10 14:46 UTC, merged